apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb-default
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: home
      defaultBucket: sensors
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-token
    isDefault: true
    editable: true
